### ISSUE TITLE
Downloading via TV or Desktop session no longer working

### ISSUE THREAD

**Issue by albertopugn** [Dniel97/RedSea#13]
I've been using RedSea successfully since its release.
Since this morning, I am unable to download via a tv or desktop session. This is the message I get when I try to authenticate or create a tv session, for example:

Traceback (most recent call last):
  File "C:\AP Temp\RedSea\redsea.py", line 560, in <module>
    main()
  File "C:\AP Temp\RedSea\redsea.py", line 73, in main
    RSF.new_session()
  File "C:\AP Temp\RedSea\redsea\sessions.py", line 65, in new_session
    super().new_session(name, username, password, device)
  File "C:\AP Temp\RedSea\redsea\tidal_api.py", line 980, in new_session
    session = TidalTvSession()
  File "C:\AP Temp\RedSea\redsea\tidal_api.py", line 652, in __init__
    self.auth()
  File "C:\AP Temp\RedSea\redsea\tidal_api.py", line 668, in auth
    self.device_code = r.json()['deviceCode']
KeyError: 'deviceCode'

Any help would be appreciated. 
Cheers

**Comment by Dniel97** [comment]
Tidal removed the support for older token such as the included `TV_TOKEN` and `DESKTOP_TOKEN`. I'm going to update the tokens in a new commit. For now only the mobile login works.

**Comment by albertopugn** [comment]
Thanks, Daniel. Looking forward to downloading the fix.

**Comment by Dniel97** [comment]
Fixed in d5aec32
