### ISSUE TITLE
Can't start mobile session

### ISSUE THREAD

**Issue by JonnyGators** [Dniel97/RedSea#27]
**Describe the bug**
When trying to start a mobile session, I get the following

Traceback (most recent call last):
  File "/home/jonathan/Music/RedSea/redsea.py", line 561, in <module>
    main()
  File "/home/jonathan/Music/RedSea/redsea.py", line 73, in main
    RSF.new_session()
  File "/home/jonathan/Music/RedSea/redsea/sessions.py", line 65, in new_session
    super().new_session(name, username, password, device)
  File "/home/jonathan/Music/RedSea/redsea/tidal_api.py", line 978, in new_session
    session = TidalMobileSession(username, password)
  File "/home/jonathan/Music/RedSea/redsea/tidal_api.py", line 474, in __init__
    self.auth(password)
  File "/home/jonathan/Music/RedSea/redsea/tidal_api.py", line 499, in auth
    raise TidalAuthError("Tidal BOT Protection, try again later!")
redsea.tidal_api.TidalAuthError: Tidal BOT Protection, try again later!

**To Reproduce**
1. Use command auth add
2. select mobile (m)
3. enter tidal username and password
4. enter name for session
5. receive useless gibberish pasted above

**Expected behavior**
Session signs in properly and allows me to proceed as normal

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Python version 

**Additional context**

**Comment by Dniel97** [comment]
Well the issue says "Tidal BOT Protection, try again later!". RedSea is depricated by now and won't receive any updates anymore, use OrpheusDL (-TIDAL) now.
