### ISSUE TITLE
Failed To download

### ISSUE THREAD

**Issue by bubundas17** [Dniel97/RedSea#9]
Currently setting this error when downloading some somgs.

```
=== Downloading track ID 141585291 ===
        Codec: MQA (Master Quality Authenticated) in FLAC container
        Track: 19
        Title: Match My Fly
        Artist: Moneybagg Yo
        Album: Time Served (Deluxe)
        ----
        100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 35.0M/35.0M [00:03<00:00, 10.8MB/s]

        Saving credits to file
Traceback (most recent call last):
  File "/home/bubun/Documents/RedSea-master/redsea.py", line 560, in <module>
    main()
  File "/home/bubun/Documents/RedSea-master/redsea.py", line 486, in main
    track_num=cur+1 if mt['type'] == 'p' else None)
  File "/home/bubun/Documents/RedSea-master/redsea/mediadownloader.py", line 518, in download_media
    f.write(lyrics_data['subtitles'].encode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'encode'
```

![image](https://user-images.githubusercontent.com/26280146/135160250-8eaae75e-49af-4e35-ac16-b8a0544e3bff.png)

**Comment by bubundas17** [comment]
And it seems like, It downloaded Same Album Multiple times.
![image](https://user-images.githubusercontent.com/26280146/135161182-53b26b42-2f85-4a2c-bcae-b697894c441e.png)
